### PR TITLE
Suggestions to #91

### PR DESCRIPTION
**Pull request by CoolSpy3**
I accidently approved #91 with pending suggestions. Thus, I've moved those suggestions to this PR.

### CODE REVIEW

**Comment by CoolSpy3** [comment]
Interestingly enough, all three workflow runs initially failed with "Webots not ready in time" but passed the second time (as of writing, mac is still in progress). Might be something to look into :/

**Comment by brettle** [comment]
> all three workflow runs initially failed with "Webots not ready in time" but passed the second time (as of writing, mac is still in progress).

Looks like issue #85 is not yet completely solved.

**Review by brettle — APPROVED** [review]
I am OK with the switch to a `Supplier`, but note that the downside is that tests will be flaky if the someone does:

```java
        var testRobot = new DBSExampleRobot() {
            // Perhaps to override some methods.
        };
        try (var manager = new WebotsSimulator(
                "../plugin/controller/src/webotsFolder/dist/worlds/DBSExample.wbt",
                () -> {
                    return testRobot;
                })) {
            // Test code..
        }
```

The instantiation of the robot will cause wpilib to try to bind to the TCP ports before the lock is acquired.

If you are ok with that, go ahead and merge.

**Comment by CoolSpy3** [comment]
Alright, I clarified the docstring to make the intended use more clear :+1:

**Pull request merged**
